mydata1 <- read.delim('household_power_consumption.txt',na.strings="?",stringsAsFactors=F, sep=";")
mydata <- subset(mydata1, Date %in% c("1/2/2007","2/2/2007"))
mydata$DateTime1 <- paste(as.Date(mydata$Date,format = "%d/%m/%Y"),mydata$Time)
mydata$DateTime <- as.POSIXct(mydata$DateTime1)
png("plot3.png",width=480,height=480)
with (mydata, {
plot(mydata$Sub_metering_1~DateTime,type="l",xlab="",ylab="Energy sub metering")
lines(mydata$Sub_metering_2~DateTime,type="l",col="red")
lines(mydata$Sub_metering_3~DateTime,type="l",col="blue")
legend("topright",col=c("black","red","blue"),cex=0.75,legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lwd=2)
})
dev.off()